ble:
  scan_interval: 5
  device_name: "BLE_Device"
  characteristic_uuid: "12345678-1234-5678-1234-56789abcdef0"

mqtt:
  broker: "mqtt-broker"
  port: 1883
  topic: "ble/data"
  client_id: "ble-gateway"