name: CD CesIoT

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: berouddylan
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image with docker-compose
        run: |
          cd ./src
          docker-compose build

      - name: Push all images
        run: |
          docker tag src-api:latest berouddylan/cesiot-api:latest
          docker tag src-mqtt-broker:latest berouddylan/cesiot-mqtt-broker:latest
          docker tag src-mobile_app:latest berouddylan/cesiot-mobile_app:latest

          docker push berouddylan/cesiot-api:latest
          docker push berouddylan/cesiot-mqtt-broker:latest
          docker push berouddylan/cesiot-mobile_app:latest
